Poll services
coschain/contentos-go pull request #10
Opened 2019-11-15 10:30 UTC by SeavantUUz

implement a new mechanism to manage blocklog-series processor

2019-11-19 09:26 UTC, dai-shuo requested changes

2019-11-19 09:26 UTC, dai-shuo commented on app/plugins/blocklog_fast_foward_manager_service.go
> +	cp.db.Last(blogLog)
this won't work with the customized table name of block logs.

2019-11-19 09:26 UTC, dai-shuo commented on app/plugins/fast_foward_manager_service.go
> +}
FastForwardManagerService & SyncForwardManagerService are just aliases of ForwardManagerService.
No necessity to define them at all. Though it's not a bug.

2019-11-19 09:26 UTC, dai-shuo commented on app/plugins/forward_manager_service.go
> +		for blockNum := minBlockNum; blockNum <= maxBlockNum; blockNum++ {
This is a ***downgrade*** of consistency.
According to my understanding, global consistency is not guaranteed any more. Instead, consistency is now in a group level. Tables are consistent only if they're maintained by the same `IBlockLogProcessor`.
Query results may be inaccurate if we need to join tables from different groups, e.g. holders & ecosys_reward.
We should discuss whether this is acceptable.

2019-11-22 07:29 UTC, dai-shuo commented on app/plugins/forward_manager_service.go
>  	point Checkpoint
`point` and `Checkpoint` in no use now

2019-11-22 08:27 UTC, dai-shuo requested changes
keep "blocklog_process" table. there're dependent services.

2019-11-22 09:24 UTC, SeavantUUz commented on app/plugins/forward_manager_service.go
>  	point Checkpoint
removed unused checkpoint now

2019-11-22 09:31 UTC, SeavantUUz commented
> keep "blocklog_process" table. there're dependent services.

2019-11-22 10:29 UTC, dai-shuo commented on app/plugins/blocklog_fast_foward_manager_service.go
> +	cp.db.Last(blogLog)
fixed by 7ddac6b

2019-11-22 10:30 UTC, dai-shuo commented on app/plugins/forward_manager_service.go
> +		for blockNum := minBlockNum; blockNum <= maxBlockNum; blockNum++ {
fixed by 7ddac6b

2019-11-22 10:31 UTC, merged